### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by AnderWoche** [Quillraven/Fleks#159]
```kotlin
override fun show() {
        val world = engine.world
        loadScreenSystem(TreasureSystem(world))
        loadScreenSystem(TileMapPathFinderSystem(world))
        loadScreenSystem(TilePathMovementSystem(world))
        loadScreenSystem(AutomaticMoveSystem(world))
        loadScreenSystem(BulletShooterSystem(world))
        loadScreenSystem(EnemyWayWalkerSystem(world)) // crash on this system
    }

    override fun hide() {
        disposeDefenceSystems()
    }

    fun loadScreenSystem(system: IntervalSystem) {
        engine.world.add(system) // it crashed here
        loadedDefenceSystems.add(system)
    }
```

stackTrace:
```kotlin
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.github.quillraven.fleks.collection.BitArray.hashCode(bitArray.kt:164)
	at com.github.quillraven.fleks.Family.hashCode(family.kt)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.getNode(HashMap.java:568)
	at java.base/java.util.LinkedHashMap.get(LinkedHashMap.java:441)
	at com.github.quillraven.fleks.World.updateAggregatedFamilyHooks(world.kt:506)
	at com.github.quillraven.fleks.World.add(world.kt:232)
	at com.github.quillraven.fleks.World.add(world.kt:242)
	at com.toiletpapertycoon.screen.screens.defence.AbstractDefenceRXScreen.loadScreenSystem(AbstractDefenceRXScreen.kt:31)
```

The System:
```kotlin
class EnemyWayWalkerSystem(world: World) : IteratingSystem(world = world, family = world.family {
    all(EnemyWayWalkerComponent)
}), FamilyOnAdd {

    private lateinit var treasureSystem: TreasureSystem

    override fun onInit() {
        treasureSystem = world.system()
    }

    override fun onAddEntity(entity: Entity) {
// empty funktion and still crashes
    }

```

**Comment by Quillraven** [comment]
Can you provide a simple example on how to reproduce it?

In general: it is not a good practice to link systems together. I see you reference a TreasureSystem and a TileMapPathFinderSystem in your EnemyWayWalkerSystem. That is not a good design. Systems should be separate and ideally don't know from each other. 

One solution would be to trigger events and a system reacts on that and does its thing. Another solution is to add components/remove components to an entity to trigger a specific other system. 

Second: You are modifying the entity configuration within a family add hook (=onAddEntity). I don't know if that works and that might be the problem with the ArrayIndexOutOfBounds, but I am not 100% sure.


Anyway, to track down the issue, please provide a simplified example where that happens. But maybe it solves itself already when you redesign your approach a little bit, keeping the best practices in my mind that I mentioned above.

**Comment by AnderWoche** [comment]
OMG,
It took me ages to recreate the problem but I managed to do it, can you take a look?

```kotlin
class AnComponent : Component<AnComponent> {
    override fun type() = AnComponent
    companion object : ComponentType<AnComponent>()
}

class StartSystem : IteratingSystem(family = family {
    all(AnComponent)
}) {
    override fun onTickEntity(entity: Entity) {}
}

class AddLaterSystem(world: World, tag: EntityTag) : IteratingSystem(world = world, family = world.family {
    all(tag)
}), FamilyOnAdd {
    override fun onInit() {}
    override fun onTickEntity(entity: Entity) {}
    override fun onAddEntity(entity: Entity) {}
}

fun main() {
    val world = configureWorld {
        systems {
            add(StartSystem())
        }
    }

    for (i in 0 until 62) {
        val entityTag = object : EntityTag() {}
        world.family { all(entityTag) }
    }

    val entityTag = object : EntityTag() {}
    println("entityTagID: ${entityTag.id}")
    val addLaterSystem = AddLaterSystem(world, entityTag)
    println("family: ${addLaterSystem.family}")
    world.add(addLaterSystem) // crash here
}
```

**Comment by Quillraven** [comment]
Nice, thank you! Seems like an issue if someone has more than 64 components. That requires a second long in the BitArray class which seems to crash the hashcode function of it.

I try to have a look on the weekend.

**Comment by AnderWoche** [comment]
Yes, you're right, this is the short version of the Crash:

```kotlin
    val bitArray = BitArray(1)
    bitArray.set(63)
    println(bitArray.hashCode()) // crash
```

**Comment by Quillraven** [comment]
It is quite interesting because I think I just use LibGDX Bits hashCode from https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/Bits.java

Either that is already broken, which I doubt, or I did a mistake somewhere in the class.

But now that we know the issue thanks to you, I think it should not be too difficult to solve it .

**Comment by Quillraven** [comment]
Is the problem solved? 🙂
